#!/bin/bash

[ -f /etc/profile ] && . /etc/profile
[ -f ~/.profile ] && . ~/.profile
[ -f /etc/xprofile ] && . /etc/xprofile
[ -f ~/.xprofile ] && . ~/.xprofile

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $sysmodmap ] && xmodmap $sysmodmap
[ -f $userresources ] && xrdb -merge $userresources
[ -f $usermodmap ] && xmodmap $usermodmap

Layout=$(grep XkbLayout /etc/X11/xorg.conf.d/10-keymap.conf|sed 's/.*"\([^"]*\)"[[:space:]]*$/\1/')
Variant=$(grep XkbVariant /etc/X11/xorg.conf.d/10-keymap.conf|sed 's/.*"\([^"]*\)"[[:space:]]*$/\1/')
Options=$(grep XkbOptions /etc/X11/xorg.conf.d/10-keymap.conf|sed 's/.*"\([^"]*\)"[[:space:]]*$/\1/')
VARIANT=" "
OPTION=" "
[ ! "$Variant" = "" ] && VARIANT="-variant $Variant"
[ ! "$Options" = "" ] && OPTION="-option $Options"
setxkbmap -layout $Layout $VARIANT $OPTION

exec $@
